language: php

cache:
    directories:
        - $HOME/.composer/cache/files

env:
    global:
        - PHPUNIT_FLAGS="-v"
        - COMPOSER_FLAGS="--prefer-dist --no-interaction"

matrix:
    fast_finish: true
    include:
        # Minimum supported dependencies with the latest and oldest PHP version
        - php: 7.4
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest --no-interaction"

        # Test the latest stable release
        - php: 7.4
          env: COVERAGE=true PHPUNIT_FLAGS="-v --coverage-text --coverage-clover=coverage.xml"

        # Latest commit to master
        - php: 7.4
          env: STABILITY="dev"

        - php: nightly
          env: STABILITY="dev" COMPOSER_FLAGS="--ignore-platform-reqs --no-interaction"

before_install:
    - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
    - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
    - if ! [ -v "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;

install:
    - composer install $COMPOSER_FLAGS --prefer-dist --no-interaction

script:
    - composer validate --strict --no-check-lock
    - vendor/bin/php-cs-fixer --allow-risky=yes --dry-run --diff --stop-on-violation fix
    - vendor/bin/psalm
    - vendor/bin/phpunit $PHPUNIT_FLAGS

after_script:
    - if [[ $COVERAGE == true ]]; then bash <(curl -s https://codecov.io/bash); fi
